client/src/components/footer.js
=> Correct URL in footer

.github/workflows/lint-server.yml, .github/workflows/server-unit-tests.yml
Updating server github workflows for linting/testing
=> refactor: updating server workflows

.github/workflows/lint-server.yml, .github/workflows/server-unit-tests.yml, server/avocano_api/cloudrun_helpers.py, server/store/tests.py
Update pytest to black, run Django tests.
=> Django tests

.github/workflows/lint-terraform.yml
=> Add Terraform Format lint test

README.walkthrough.md, provisioning/terraform/apis.tf, provisioning/terraform/firebase.tf, provisioning/terraform/jobs.tf, provisioning/terraform/main.tf, provisioning/terraform/storage.tf, setup.sh
=> Move jobs, firebase to terraform

docs/admin/README.md, docs/admin/testing-changes.md
=> Document how to apply testing to preview environment

cloudbuild.yaml
=> No longer need to manually sed, handled in rollup.config.js

provisioning/automation/cloudbuild.yaml
=> Firebase is now enabled in terraform, don't enable separately

docs/django/apply-migrations.md, setup.sh
=> rename migrate-database to migrate

docs/admin/testing-changes.md
=> Rename cloud build trigger to something useful

cloudbuild.yaml, provisioning/terraform.cloudbuild.yaml, provisioning/terraform/apis.tf, provisioning/terraform/container.tf, provisioning/terraform/database.tf, provisioning/terraform/firebase.tf, provisioning/terraform/iam.tf, provisioning/terraform/jobs.tf, provisioning/terraform/main.tf, provisioning/terraform/output.tf, provisioning/terraform/service.tf, provisioning/terraform/storage.tf, provisioning/terraform/variables.tf
=> Terraform improvements

.github/workflows/auto-label.yml
**Fixes:** Adds auto-label.yml config for auto-label bot
=> feat: adding initial auto-label config

client/README.md, client/firebase.json, client/index.html, client/web-dev-server.config.mjs
**Fixes:** Chore work. Small update to client README doc and minor linting fixes.
=> refactor: updating client readme

client/Dockerfile, provisioning/client-image.cloudbuild.yaml, provisioning/terraform/container.tf, provisioning/terraform/jobs.tf, setup.sh
Allows for deploying front end with a Cloud Run job.
=> Deploy client with Cloud Run job, image

provisioning/automation/cloudbuild.yaml
=> Fix syntax error

client/Dockerfile, client/README.md, client/docker-deploy.sh
This PR works with #44, allowing for the customisation of the region and service name in the firebase rewrites configuration.
=> Add client-image customisation script

provisioning/terraform/jobs.tf
=> Ensure job isn't created without API being enabled

provisioning/automation/cloudbuild.yaml, provisioning/terraform/jobs.tf
=> Integration tests include client tests as standard

server/avocano_api/settings.py
=> Allow cloudshell.dev for local dev

docs/django/apply-migrations.md
Clarifies running the server migration step as part of normal operations. 
As suggested by @grayside 
=> Cleanup server migrate step

provisioning/client-image.cloudbuild.yaml, provisioning/server.cloudbuild.yaml
No changes required to client code/docs. 
Allows for customising the image name for other processes. 
=> Allow custom image names (for upstream triggers)

cloudbuild.yaml, docs/admin/extending-example.md, provisioning/automation/project-setup.sh, provisioning/terraform.cloudbuild.yaml, provisioning/terraform/.gitignore, provisioning/terraform/main.tf, provisioning/terraform/state.tf
Instead of writing a state file, you can set `-backend-config` on init. 
TIL via @grayside 
=> Dynamically set TF bucket on init

docs/admin/README.md
=> Document management commands and usage

docs/admin/management-commands.md
Fixes #79 
Actually committing the file, this time 😅 
=> Add management command doc

README.md
=> feat: init release tags

provisioning/tagged-images.cloudbuild.yaml
Instead of adjusting existing configurations, introduce a new one specifically using `$TAG_NAME`
=> feat: introduce tagged image build configuration

provisioning/tagged-images.cloudbuild.yaml
=> fix: syntax

cloudbuild.yaml, provisioning/test/test.cloudbuild.yaml
=> fix: ensure playwright gets test flag

server/avocano_api/settings.py
=> Correct cloudshell_host to support subdomains

.github/conventional-commit-lint.yaml
Fixes issues where #142 didn't fire release-please
=> fix: add conventional commit check

release-please-config.json
Fixes #177 
Also, add some sparkle ✨
=> chore: declare changelog sections

renovate.json
=> fix: renovate matchPaths syntax

client/package-lock.json, client/package.json
=> chore(deps): replace direct dependency on deprecated rollup-plugin-terser

.github/ISSUE_TEMPLATE/bug-report.md
=> Update bug-report.md: Add type and priority labels

cloudbuild.yaml, docs/admin/extending-example.md, docs/admin/management-commands.md, docs/django/apply-migrations.md, provisioning/terraform/jobs.tf, setup.sh
=> feat: update Cloud Run Jobs to GA, remove beta references

provisioning/terraform/service.tf
=> fix: remove startup probe

client/docker-deploy.sh
=> fix(minor): formatting shell script

provisioning/terraform/service.tf
=> Update Cloud Run service to better map to v2 TF 

client/package-lock.json, client/package.json, client/src/components/checkout-form.js
Fixes #149 
To verify:
* Follow steps to run locally https://github.com/GoogleCloudPlatform/avocano/tree/main/client
* Add a product to your cart
* Attempt to check out and ensure that:
* purchase button is disabled if no email input 
* purchase button is disabled when email is not correct format
* purchase button is enabled when email is in correct format
=> fix(issue-149): update email validation on input change

.github/workflows/lint-server.yml, provisioning/test/client_test.py, provisioning/test/server_test.py, server/avocano_api/healthchecks.py, server/store/management/commands/create_site_config.py, server/store/management/commands/generate_testimonials.py, server/store/migrations/0003_alter_testimonial_reviewer_location.py, server/store/migrations/0004_alter_siteconfig_base_font_and_more.py, server/store/tests.py
- fix: run black with --check to report formatting errors
- black format all python code
Part of #270
=> fix: correct python linter to error on formatting problems

README.walkthrough.md
Fixes #267
Fix the typo in the "Manage infrastructure as code" link
- [x ] Added steps to reproduce the changes in this pull request
- [ x] Added relevant testing in this pull request
- [x ] Please **merge** this PR for me once it is approved.
No code change.
=> Fix typo in README.walkthrough.md

cloudbuild.yaml, provisioning/automation/cloudbuild.yaml, provisioning/test/README.md, provisioning/test/test.cloudbuild.yaml
Fixes #277
Merges to main and any other tests that do UI validation will fail until this is merged
=> Update to Python 3.11, downgrade to Debian 11 for Playwright

provisioning/automation/admin-project-setup.sh
Fixes #279, thanks to @chgans for the report!
=> fix: remove extra pipe from shell command

.github/header-check-lint.yml
Resolves error in #290 
(In theory the lint change should be able to be added in the same PR, but for some reason it's not working, so creating a separate PR to get the change in first)
=> fix: add headerlint ignore for #290

client/package-lock.json
Update several packages giving CLI warnings on dev machine
=> chore: npm audit fix

client/package-lock.json, client/package.json, client/src/components/checkout-dialog.js, client/src/components/product-item.js, client/src/helpers/checkout.js, client/src/pages/checkout.js, client/src/pages/product-list.js, client/src/utils/fetch.js, client/test/components/product-item.test.js, client/test/pages/checkout.test.js, client/test/pages/contact.test.js, client/test/pages/product-list.test.js, client/test/pages/product.test.js, client/test/pages/shipping.test.js
Replaces #306 
Update to prettier v3, and apply the suggested format changes. 
[Breaking changes](https://prettier.io/blog/2023/07/05/3.0.0.html#breaking-changes), including (most obvious in delta)
* [Change the default value for trailingComma to all](https://prettier.io/blog/2023/07/05/3.0.0.html#change-the-default-value-for-trailingcomma-to-all-11479httpsgithubcomprettierprettierpull11479-by-fiskerhttpsgithubcomfisker-13143httpsgithubcomprettierprettierpull13143-by-sosukesuzukihttpsgithubcomsosukesuzuki)
* Decorator pattern changes (unsure which specific change, but there are a few similar).
=> chores(deps): update dependency prettier to v3, and format

provisioning/test/client_test.py, provisioning/test/conftest.py, provisioning/test/requirements.txt, provisioning/test/server_test.py
Fixes #195 
Adds additional tests for server API logic
=> chore: Add additional tests to cart logic

docs/README.md
=> chore: add reference to jump start

provisioning/terraform/main.tf, provisioning/terraform/secrets.tf
Fixes described in #357 
Replaces #362, branched for automated testing and updates qhere required. 
=> chore(deps): update terraform google to v5

README.walkthrough.md, client/Dockerfile, cloudbuild.yaml, docs/admin/README.md, docs/admin/artifact-registry.md, docs/admin/management-commands.md, docs/admin/terraform-latest.md, provisioning/automation/admin-project-setup.sh, provisioning/automation/project-setup.sh, provisioning/client-image.cloudbuild.yaml, provisioning/client.cloudbuild.yaml, provisioning/firebase-builder.cloudbuild.yaml, provisioning/server.cloudbuild.yaml, provisioning/tagged-images.cloudbuild.yaml, provisioning/terraform/container.tf, provisioning/terraform/jobs.tf, provisioning/terraform/service.tf, setup.sh
Removes Container Registry for Artifact Registry. 
Major changes: 
* Creating an Artifact Registry repository on setup, along with appropriate IAM roles and API enablings
* `s/gcr.io/us-docker.pkg.dev/`
* Update `latest` image logic 
Resolves #253 
=> feat: Migrate from Container Registry to Artifact Registry

.github/labeler.yml
Resolves issues introduced in #409
=> Update labeler to v5 syntax

.github/workflows/client-unit-tests.yml, .github/workflows/lint-client.yml, client/eslint.config.js, client/package-lock.json, client/package.json, client/src/components/cart-item.js, client/src/components/checkout-form.js, client/src/components/product-item.js, client/test/pages/checkout.test.js, client/web-dev-server.config.mjs
=> deps: update eslint to v9, formatting

.github/workflows/auto-label.yml, .github/workflows/review-warning.yml
Add some guidance on safe usage of `pull_request_target`. Initial PR is providing minimal information.
=> ci: Add inline guidance on pull_request_target usage

server/store/admin.py
Results of running https://github.com/adamchainz/django-upgrade#usage across the `server/` directory. Compliments the manual update completed in #467
=> chore: django-upgrade suggestions

cloudbuild.yaml, provisioning/server.cloudbuild.yaml, provisioning/tagged-images.cloudbuild.yaml
Uses https://hub.docker.com/r/buildpacksio/pack for image creation
=> feat: update pack image to dockerhub version
