GoogleCloudPlatform/avocano

- client/src/components/product-item.js
**Fixes:** #25 
**To reproduce:**
Originally, if a product (i.e `/product/4`) was bought that is not the main product at root (`/`) - you'll be suddenly redirected to root. 
**To ensure this has been resolved:**
* Check this PR out
* Select product from purchase list `/product/{id}`
* Click `Buy` button and verify that you are not redirected and that an Oops modal pops up. Product count should also decrement after every click.
> fix(issue-25): tiny prevent default fix when a product is purchased

- cloudbuild.yaml
- docs/admin/testing-changes.md
- provisioning/automation/README.md
- provisioning/automation/cloudbuild.yaml
- provisioning/automation/test.cloudbuild.yaml
- provisioning/server.update.sh
- provisioning/test/README.md
This adds a step to the global `cloudbuild.yaml` to optionally run playwright tests. 
`gcloud builds submit` still runs, and will add 00:00:03 to tests just to confirm the flag isn't set. 
But if you run `gcloud builds submit --substitutions _RUN_TESTS=yes`, ~2 minutes is added to tests that will validate deployments. 
This flag can be run by admins on infra automation, and nightly tests, without affecting user deployments.
> Add optionally run playwright tests

- .github/pull_request_template.md
PR #67 didn't automatically close #66. The PR included: 
```
**Fixes**: #66 
```
I'm not sure if it's the formatting or the `:`, but this didn't automatically match. [GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) say it must be in the form `KEYWORD #ISSUE-NUMBER`, so remove both formatting and `:`.
> Update PR template to enable automatching

- client/README.md
Running `npm build` in my client directory results in:
```
➜  client git:(main) ✗ npm build
Unknown command: "build"
Did you mean this?
npm run build # run the "build" package script
To see a list of supported npm commands, run:
npm help
```
But `npm run build` works 👍 
```
➜  client git:(main) ✗ npm run build
> avocano-app@0.0.1 build
> rimraf dist && rollup -c rollup.config.js
404.html → dist...
created dist in 8ms
index.html → dist...
The service worker file was written to dist/sw.js
The service worker will precache 4 URLs, totaling 138 kB.
created dist in 1.8s
```
> Client docs: s/npm build/npm run build

- client/README.md
Fixes #124
Hello, I found publicly inaccessible URLs in the docs. Thanks. 🙂 
To check the change, try accessing the new URL.
> docs: replace Google internal URL with the public one

- renovate.json
* Playwright dependencies must be kept in close synchronization
* OpenTelemetry Python libraries must be kept in close sync
* Renovate by default will only open 10 PRs, without the dependency dashboard issue it's hard to see if there are more. This change includes a tweak allowing renovate to open as many PRs as it thinks are necessary, which improves our PR-based visibility into the amount of update work to be done.
> Update renovate: Group OTel & Playwright, & unlimited open PRs

- client/Dockerfile
This advances work on #147 for the client container by adding image labels, or annotations, to the client dockerfile.
Annotations such as this are not particularly surfaced in Cloud products, but if you have the container image you can examine with docker inspect.
A more targeted inspection can pull just the annotation we want out:
```
docker inspect --format='{{index .Config.Labels "dev.avocano.purchase_mode"}}' avocano-client-image
cart
```
I would have preferred to extend this further with Avocano version and build timestamp, but those would require adding more build args and I've deliberately made this change least impact.
> feat: Add container annotations for title, description, and purchase_mode

- server/avocano_api/settings.py
Correctly set CORS hosts, and specifically allow including credentials, to allow for local development of Avocano. 
Fixes #97 
Tested in: 
* Local development
* Cloud Shell
* Isolated deployment to Cloud Run + Firebase
> fix: correct cors issues in local development

- renovate.json
Dependency dashboard is how we can investigate and control renovate behavior.
paths is a deprecated property, it should be a non-functional change.
> chore: re-enable renovate dependency dashboard

- .github/workflows/auto-label.yml
This change may not work in practice, it is meant to disable a default behavior of applying an ignore-for-release label to chore PRs.
https://github.com/bcoe/conventional-release-labels/blob/main/action.yml#L14
> Update auto-label.yml: Do not apply ignore-for-release label to chores

- .github/workflows/review-warning.yml
Fix the review-warning workflow error found in #219. If this works, port the change to tdpwa
> chore: use pull_request_target for GHA commenting workflow

- server/avocano_api/settings.py
Fixes #269 
PR and release required before creating PR in Terraform to suit. 
https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/commit/57a7d542804ce886565aa1cc1eaac1b3baf5d8e8
> fix: support deployment suffix IDs to customise CSRF trusted domains

- .github/workflows/lint-terraform.yml
- provisioning/terraform/apis.tf
This should cause the `terraform fmt` to correctly exit non-zero when
encountering a tf formatting error.
As suggested by @chgans
Part of #270
> testing: terraform linter exit code fix

- provisioning/terraform/service.tf
Fixes #257
From the original annotations pre #240: 
* Add client ("Arbitrary identifier for the API client.") in this PR
* Cloud SQL was moved to volumes
* maxScale is optional, was using the default value
> fix: restore client annotation to cloud run service

- provisioning/terraform/service.tf
Reference #74 
Restores the startup probe in #225, with better behaving configuration values.
> fix: restore startup probe, 1s period

- .github/header-checker-lint.yml
Fixes check failures on #309
version.txt is parsed directly as a version number, and having licence headers on requirements*.txt files is unusual
Therefore, this these are all the .txt files in the repo, remove the requirement for txt files to have licence headers.
> fix: Remove .txt files from requiring licence headers

- provisioning/terraform/main.tf
Fixes #355 #354 #353 
Breaking deprecations and changes in the newly released Terraform Google Provider 5.0.0 means we should pin this to the 4.x branch until we can update for this new major release
> fix: pin google provider < 5.0.0

- server/avocano_api/cloudrun_helpers.py
- server/avocano_api/settings.py
Fixes #493
Changes CLOUDRUN_SERVICE_URL to support a list of URLs from the "run.googleapis.com/urls" annotation for CSRF. 
Opted to not pluralise this URL, but update it to presume it's a string, with possible comma separation. 
This also may not require `run.viewer` on the server service account any more, which will need to be updated with the tf updates.
> feat: handle deterministic URLs

- server/avocano_api/cloudrun_helpers.py
- server/requirements.txt
Fixes #497
Service object from google-cloud-run doesn't return metadata dict; but discovery API does. 
Not noticed in validation in #497 because manual e2e testing is required (older infra setup on this repo)
> fix: use metadata-aware client sdk

- cloudbuild.yaml
- provisioning/automation/cloudbuild.yaml
Reverts GoogleCloudPlatform/avocano#517
Nested dependencies mean that an older version of greenlet is being installed that isn't building correctly with Python 3.13 (only affects nightly builds, not PR builds). This PR only updated to Python 3.13 for testing, not the main application, so best to keep everything on Python 3.12 for now.
> Revert "chore(deps): update python docker tag to v3.13"
